services:

  mysql:
    image: mysql:8
    container_name: ghost-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - /data/mysql:/var/lib/mysql

    ports:
      - "3307:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  ghost-blue:
    image: koushiksiripuram/ghost-app:latest
    container_name: ghost-blue
    restart: always

    expose:
    - "2368"

    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - /data/ghost:/var/lib/ghost/content
      - /data/ghost-logs/blue:/var/lib/ghost/content/logs
      - ../content/themes:/var/lib/ghost/content/themes

    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
      url: https://ghostapp.duckdns.org

  ghost-green:
    image: koushiksiripuram/ghost-app:latest
    container_name: ghost-green
    restart: "no"

    expose:
      - "2368"

    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - /data/ghost:/var/lib/ghost/content
      - /data/ghost-logs/green:/var/lib/ghost/content/logs
      - ../content/themes:/var/lib/ghost/content/themes

    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
      url: https://ghostapp.duckdns.org

  nginx:
    image: nginx:alpine
    container_name: ghost-nginx
    restart: always

    depends_on:
      - ghost-blue

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot

  #   volumes:
  #     - /data/certbot/www:/var/www/certbot
  #     - /data/certbot/conf:/etc/letsencrypt









