pipeline {

    agent any

    environment {

        IMAGE_NAME = "koushiksiripuram/ghost-app"
        IMAGE_TAG = "${BUILD_NUMBER}"

        EC2_HOST ="${env.EC2_HOST}"
        S3_BUCKET = "${env.S3_BUCKET}"
        ALERT_EMAIL = "${env.ALERT_EMAIL}"
        TF_lOCK_TABLE = "${env.TF_LOCK_TABLE}"
    }

    stages {

        stage('Build Docker Image') {

            steps {

                sh "docker rmi $IMAGE_NAME:$IMAGE_TAG || true"

                sh """
                docker build --no-cache \
                -f app/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
                """
            }
        }

        stage('Docker Hub Login') {

            steps {

                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {

            steps {

                sh "docker push $IMAGE_NAME:$IMAGE_TAG"
            }
        }

        stage('Terraform Init') {

            steps {

                dir('terraform') {

                    sh '''
                    terraform init \
            -backend-config="bucket=$S3_BUCKET" \
            -backend-config="dynamodb_table=$TF_LOCK_TABLE"
                    '''
                    sh 'terraform plan -var="public_ip=$EC2_HOST" -var="mail_endpoint=$ALERT_EMAIL"'
                }
            }
        }

        stage('Terraform Apply') {

            steps {

                dir('terraform') {

                    sh 'terraform apply -auto-approve -var="public_ip=$EC2_HOST" -var="mail_endpoint=$ALERT_EMAIL"'
                    script {
    env.APP_IP = sh(
        script: 'terraform output -raw app_private_ip',
        returnStdout: true
    ).trim()
}

echo "APP_IP=${env.APP_IP}"
                }
            }
        }

        stage('Wait For EC2') {

            steps {

                sh 'sleep 60'
            }
        }
        


        stage('Deploy To EC2') {

            steps {

        sh """
aws s3 cp s3://$S3_BUCKET/master.pem /tmp/master.pem
chmod 400 /tmp/master.pem

aws s3 cp s3://$S3_BUCKET/certbot-conf.tar.gz .
aws s3 cp s3://$S3_BUCKET/ghost.env ghost.env

scp -o StrictHostKeyChecking=no \
-i /tmp/master.pem \
certbot-conf.tar.gz ghost.env scripts/deploy.sh \
ubuntu@$APP_IP:/home/ubuntu/

ssh -o StrictHostKeyChecking=no \
-i /tmp/master.pem ubuntu@$APP_IP \
"chmod +x /home/ubuntu/deploy.sh && IMAGE_NAME=${IMAGE_NAME} IMAGE_TAG=${IMAGE_TAG} bash /home/ubuntu/deploy.sh"
"""
    }
}
        

        stage('Health Check') {

    steps {

         sh """
scp -o StrictHostKeyChecking=no \
-i /tmp/master.pem \
scripts/health-check.sh \
ubuntu@$APP_IP:/home/ubuntu/

ssh -o StrictHostKeyChecking=no \
-i /tmp/master.pem ubuntu@$APP_IP \
"chmod +x /home/ubuntu/health.sh && bash /home/ubuntu/health.sh"
"""
    }
}


    }

    post {

        success {

            echo 'Deployment completed successfully!'
        }

        failure {

            echo 'Pipeline failed !'
        }
    }
}
//new file