pipeline {

    agent any

    environment {

        IMAGE_NAME = "koushiksiripuram/ghost-app"
        IMAGE_TAG = "${BUILD_NUMBER}"

        EC2_HOST ="${env.EC2_HOST}"
        S3_BUCKET = "${env.S3_BUCKET}"
        ALERT_EMAIL = "${env.ALERT_EMAIL}"
        TF_lOCK_TABLE = "${env.TF_LOCK_TABLE}"
    }

    stages {

        stage('Build Docker Image') {

            steps {

                sh "docker rmi $IMAGE_NAME:$IMAGE_TAG || true"

                sh """
                docker build --no-cache \
                -f app/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
                """
            }
        }

        stage('Docker Hub Login') {

            steps {

                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {

            steps {

                sh "docker push $IMAGE_NAME:$IMAGE_TAG"
            }
        }

        stage('Terraform Init') {

            steps {

                dir('terraform') {

                    sh '''
                    terraform init \
            -backend-config="bucket=$S3_BUCKET" \
            -backend-config="dynamodb_table=$TF_LOCK_TABLE"
                    '''
                    sh 'terraform plan -var="public_ip=$EC2_HOST" -var="mail_endpoint=$ALERT_EMAIL"'
                }
            }
        }

        stage('Terraform Apply') {

            steps {

                dir('terraform') {

                    sh 'terraform apply -auto-approve -var="public_ip=$EC2_HOST" -var="mail_endpoint=$ALERT_EMAIL"'
                    script {
    env.APP_IP = sh(
        script: 'terraform output -raw app_private_ip',
        returnStdout: true
    ).trim()
}

echo "APP_IP=${env.APP_IP}"
                }
            }
        }

        stage('Wait For EC2') {

            steps {

                sh 'sleep 60'
            }
        }

        stage('Deploy To EC2') {

            steps {

                sh """
aws s3 cp s3://$S3_BUCKET/master.pem /tmp/master.pem

chmod 400 /tmp/master.pem

aws s3 cp s3://$S3_BUCKET/certbot-conf.tar.gz .
aws s3 cp s3://$S3_BUCKET/ghost.env ghost.env
scp -o StrictHostKeyChecking=no \
-i /tmp/master.pem \
certbot-conf.tar.gz ghost.env \
ubuntu@$APP_IP:/home/ubuntu/

ssh -o StrictHostKeyChecking=no \
-i /tmp/master.pem ubuntu@$APP_IP << EOF
sudo mkdir -p /data/ghost
sudo mkdir -p /data/mysql
if ! mountpoint -q /data/ghost; then

    if ! blkid /dev/nvme1n1 > /dev/null 2>&1; then
        sudo mkfs.ext4 /dev/nvme1n1
    fi

    sudo mount /dev/nvme1n1 /data/ghost || true

    grep -q "/data/ghost" /etc/fstab || \
    echo '/dev/nvme1n1 /data/ghost ext4 defaults,nofail 0 2' | sudo tee -a /etc/fstab
fi

if ! mountpoint -q /data/mysql; then

    if ! blkid /dev/nvme1n1 > /dev/null 2>&1; then
        sudo mkfs.ext4 /dev/nvme1n1
    fi

    sudo mount /dev/nvme1n1 /data/mysql || true

    grep -q "/data/mysql" /etc/fstab || \
    echo '/dev/nvme1n1 /data/mysql ext4 defaults,nofail 0 2' | sudo tee -a /etc/fstab
fi
rm -rf app

git clone https://github.com/koushiksiripuram/end_to_end.git app

mv /home/ubuntu/certbot-conf.tar.gz /home/ubuntu/app/docker/
mv /home/ubuntu/ghost.env /home/ubuntu/app/docker/.env

cd /home/ubuntu/app/docker

tar -xzvf certbot-conf.tar.gz

sed -i '/  ghost:/,/  nginx:/ s|image: .*|image: '"${IMAGE_NAME}:${IMAGE_TAG}"'|' docker-compose.yaml

cd ../scripts

chmod +x install.sh
./install.sh

sudo systemctl enable docker

sudo systemctl start docker

cd ../docker

sudo docker compose down --remove-orphans

sudo docker network prune -f

sudo docker image rm ${IMAGE_NAME}:${IMAGE_TAG} || true

sudo docker compose pull

sudo docker compose up -d --force-recreate

EOF
"""
            }
        }

        stage('Health Check') {

            steps {

                sh """
sleep 30

curl -Ik https://ghostapp.duckdns.org
"""
            }
        }
    }

    post {

        success {

            echo 'Deployment completed successfully!'
        }

        failure {

            echo 'Pipeline failed!'
        }
    }
}
//new file